# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Catalogo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName("root")
        root.resize(705, 467)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(root.sizePolicy().hasHeightForWidth())
        root.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        root.setFont(font)
        root.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/RS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        root.setWindowIcon(icon)
        root.setToolTipDuration(-1)
        root.setLayoutDirection(QtCore.Qt.RightToLeft)
        root.setDocumentMode(True)
        root.setDockNestingEnabled(True)
        root.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(root)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableView(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(6, 252, 691, 210))
        self.table.setStyleSheet("border: 2px solid black;")
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.table.setObjectName("table")
        self.button_adicionar = QtWidgets.QPushButton(self.centralwidget)
        self.button_adicionar.setGeometry(QtCore.QRect(6, 210, 90, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_adicionar.setFont(font)
        self.button_adicionar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_adicionar.setAutoFillBackground(False)
        self.button_adicionar.setAutoDefault(True)
        self.button_adicionar.setDefault(True)
        self.button_adicionar.setFlat(False)
        self.button_adicionar.setObjectName("button_adicionar")
        self.label_imagem = QtWidgets.QLabel(self.centralwidget)
        self.label_imagem.setGeometry(QtCore.QRect(605, 30, 90, 90))
        self.label_imagem.setToolTipDuration(-1)
        self.label_imagem.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_imagem.setAutoFillBackground(False)
        self.label_imagem.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"borader-radius:2px;\n"
"border: 2px solid black;")
        self.label_imagem.setLineWidth(0)
        self.label_imagem.setText("")
        self.label_imagem.setPixmap(QtGui.QPixmap("img/RS.png"))
        self.label_imagem.setScaledContents(True)
        self.label_imagem.setAlignment(QtCore.Qt.AlignCenter)
        self.label_imagem.setWordWrap(True)
        self.label_imagem.setIndent(7)
        self.label_imagem.setOpenExternalLinks(False)
        self.label_imagem.setObjectName("label_imagem")
        self.button_buscar = QtWidgets.QPushButton(self.centralwidget)
        self.button_buscar.setGeometry(QtCore.QRect(108, 210, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_buscar.setFont(font)
        self.button_buscar.setAutoDefault(True)
        self.button_buscar.setDefault(True)
        self.button_buscar.setFlat(False)
        self.button_buscar.setObjectName("button_buscar")
        self.text_descricao = QtWidgets.QTextEdit(self.centralwidget)
        self.text_descricao.setGeometry(QtCore.QRect(267, 30, 331, 151))
        self.text_descricao.setStyleSheet("border: 2px solid black;")
        self.text_descricao.setObjectName("text_descricao")
        self.label_descricao = QtWidgets.QLabel(self.centralwidget)
        self.label_descricao.setGeometry(QtCore.QRect(187, 31, 74, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_descricao.setFont(font)
        self.label_descricao.setStyleSheet("border:1px solid black;\n"
"background-color: rgb(218, 218, 218);")
        self.label_descricao.setObjectName("label_descricao")
        self.combobox_status = QtWidgets.QComboBox(self.centralwidget)
        self.combobox_status.setGeometry(QtCore.QRect(75, 180, 135, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combobox_status.sizePolicy().hasHeightForWidth())
        self.combobox_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.combobox_status.setFont(font)
        self.combobox_status.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.combobox_status.setAutoFillBackground(False)
        self.combobox_status.setStyleSheet("border:1px solid black;")
        self.combobox_status.setEditable(False)
        self.combobox_status.setDuplicatesEnabled(False)
        self.combobox_status.setObjectName("combobox_status")
        self.combobox_status.addItem("")
        self.combobox_status.setItemText(0, "")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.combobox_status.addItem("")
        self.button_imagem = QtWidgets.QPushButton(self.centralwidget)
        self.button_imagem.setGeometry(QtCore.QRect(606, 129, 90, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_imagem.setFont(font)
        self.button_imagem.setAutoDefault(True)
        self.button_imagem.setDefault(True)
        self.button_imagem.setObjectName("button_imagem")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(8, 180, 56, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border:1px solid black;")
        self.label_status.setObjectName("label_status")
        self.button_limpar = QtWidgets.QPushButton(self.centralwidget)
        self.button_limpar.setGeometry(QtCore.QRect(193, 210, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_limpar.setFont(font)
        self.button_limpar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_limpar.setAutoFillBackground(False)
        self.button_limpar.setAutoDefault(True)
        self.button_limpar.setDefault(True)
        self.button_limpar.setObjectName("button_limpar")
        self.button_remover = QtWidgets.QPushButton(self.centralwidget)
        self.button_remover.setGeometry(QtCore.QRect(278, 210, 70, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_remover.setFont(font)
        self.button_remover.setAutoDefault(True)
        self.button_remover.setDefault(True)
        self.button_remover.setObjectName("button_remover")

        self.entry_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.entry_nome.setGeometry(QtCore.QRect(130, 60, 131, 20))
        self.entry_nome.setStyleSheet("border:1px solid black;")
        self.entry_nome.setObjectName("entry_nome")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(7, 60, 103, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome.setFont(font)
        self.label_nome.setMouseTracking(False)
        self.label_nome.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border: 1px solid black;")
        self.label_nome.setObjectName("label_nome")
        root.setCentralWidget(self.centralwidget)

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        _translate = QtCore.QCoreApplication.translate
        root.setWindowTitle(_translate("root", "root"))
        self.button_adicionar.setText(_translate("root", "Cadastrar"))
        self.button_buscar.setText(_translate("root", "Buscar"))
        self.label_descricao.setText(_translate("root", "Descrição:"))
        self.combobox_status.setItemText(1, _translate("root", "Pouco precoupante"))
        self.combobox_status.setItemText(2, _translate("root", "Preocupante"))
        self.combobox_status.setItemText(3, _translate("root", "Alerta"))
        self.combobox_status.setItemText(4, _translate("root", "Em Extinção"))
        self.combobox_status.setItemText(5, _translate("root", "Crítico"))
        self.combobox_status.setItemText(6, _translate("root", "Extinto"))
        self.button_imagem.setText(_translate("root", "Imagem"))
        self.label_status.setText(_translate("root", "Status:"))
        self.button_limpar.setText(_translate("root", "Limpar"))
        self.button_remover.setText(_translate("root", "Deletar"))
        self.label_nome.setText(_translate("root", "Nome da Espécie:"))

    def criar_tabela(self):
        """Cria a tabela no banco de dados, se não existir"""
        self.cursor.execute("""
            CREATE TABLE IF NOT EXISTS especies (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT UNIQUE NOT NULL,
                status TEXT,
                descricao TEXT,
                imagem BLOB
            )
        """)
        self.conn.commit()
    def carregar_imagem(self):
        """Abre o seletor de arquivos para escolher uma imagem e exibi-la na tela"""
        options = QFileDialog.Options()
        file_path, _ = QFileDialog.getOpenFileName(None, "Selecionar Imagem", "",
                                                   "Imagens (*.png *.jpg *.jpeg *.bmp);;", options=options)

        if file_path:
            self.caminho_imagem = file_path
            pixmap = QtGui.QPixmap(file_path)
            self.label_imagem.setPixmap(pixmap)

    def listar_especies(self):
        """Carrega os dados do banco de dados e exibe na tabela"""
        self.cursor.execute("SELECT nome, descricao, status FROM especies")
        dados = self.cursor.fetchall()

        self.table.setRowCount(len(dados))
        for row_index, row_data in enumerate(dados):
            for col_index, cell_data in enumerate(row_data):
                self.table.setItem(row_index, col_index, QtWidgets.QTableWidgetItem(str(cell_data)))

    def limpar_campos(self):
        """Limpa os campos do formulário"""
        self.text_descricao.clear()
        self.combobox_status.setCurrentIndex(0)
        self.label_imagem.clear()
        self.caminho_imagem = None
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    root = QtWidgets.QMainWindow()
    ui = Ui_root()
    ui.setupUi(root)
    root.show()
    sys.exit(app.exec_())
